name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      TF_VAR_morpheus_url: ${{ secrets.TF_VAR_MORPHEUS_URL }}
      TF_VAR_morpheus_access_token: ${{ secrets.TF_VAR_MORPHEUS_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Download Morpheus Provider
        run: |
          curl -LO https://github.com/gomorpheus/terraform-provider-morpheus/releases/download/v0.4.3/terraform-provider-morpheus_0.4.3_linux_amd64.zip
          mkdir -p terraform.d/plugins/morpheusdata.com/gomorpheus/morpheus/0.4.3/linux_amd64
          unzip terraform-provider-morpheus_0.4.3_linux_amd64.zip -d terraform.d/plugins/morpheusdata.com/gomorpheus/morpheus/0.4.3/linux_amd64
          chmod +x terraform.d/plugins/morpheusdata.com/gomorpheus/morpheus/0.4.3/linux_amd64/terraform-provider-morpheus_v0.4.3

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
